// Generated by gencpp from file robot_core/ArmBatchTransform.msg
// DO NOT EDIT!


#ifndef ROBOT_CORE_MESSAGE_ARMBATCHTRANSFORM_H
#define ROBOT_CORE_MESSAGE_ARMBATCHTRANSFORM_H

#include <ros/service_traits.h>


#include <robot_core/ArmBatchTransformRequest.h>
#include <robot_core/ArmBatchTransformResponse.h>


namespace robot_core
{

struct ArmBatchTransform
{

typedef ArmBatchTransformRequest Request;
typedef ArmBatchTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmBatchTransform
} // namespace robot_core


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_core::ArmBatchTransform > {
  static const char* value()
  {
    return "6007fc72702fa9d4c127d034c134e06f";
  }

  static const char* value(const ::robot_core::ArmBatchTransform&) { return value(); }
};

template<>
struct DataType< ::robot_core::ArmBatchTransform > {
  static const char* value()
  {
    return "robot_core/ArmBatchTransform";
  }

  static const char* value(const ::robot_core::ArmBatchTransform&) { return value(); }
};


// service_traits::MD5Sum< ::robot_core::ArmBatchTransformRequest> should match
// service_traits::MD5Sum< ::robot_core::ArmBatchTransform >
template<>
struct MD5Sum< ::robot_core::ArmBatchTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_core::ArmBatchTransform >::value();
  }
  static const char* value(const ::robot_core::ArmBatchTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_core::ArmBatchTransformRequest> should match
// service_traits::DataType< ::robot_core::ArmBatchTransform >
template<>
struct DataType< ::robot_core::ArmBatchTransformRequest>
{
  static const char* value()
  {
    return DataType< ::robot_core::ArmBatchTransform >::value();
  }
  static const char* value(const ::robot_core::ArmBatchTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_core::ArmBatchTransformResponse> should match
// service_traits::MD5Sum< ::robot_core::ArmBatchTransform >
template<>
struct MD5Sum< ::robot_core::ArmBatchTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_core::ArmBatchTransform >::value();
  }
  static const char* value(const ::robot_core::ArmBatchTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_core::ArmBatchTransformResponse> should match
// service_traits::DataType< ::robot_core::ArmBatchTransform >
template<>
struct DataType< ::robot_core::ArmBatchTransformResponse>
{
  static const char* value()
  {
    return DataType< ::robot_core::ArmBatchTransform >::value();
  }
  static const char* value(const ::robot_core::ArmBatchTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_CORE_MESSAGE_ARMBATCHTRANSFORM_H
