// Generated by gencpp from file robot_core/ArmBatchTransformRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_CORE_MESSAGE_ARMBATCHTRANSFORMREQUEST_H
#define ROBOT_CORE_MESSAGE_ARMBATCHTRANSFORMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace robot_core
{
template <class ContainerAllocator>
struct ArmBatchTransformRequest_
{
  typedef ArmBatchTransformRequest_<ContainerAllocator> Type;

  ArmBatchTransformRequest_()
    : ids()
    , points()
    , arm(0)  {
    }
  ArmBatchTransformRequest_(const ContainerAllocator& _alloc)
    : ids(_alloc)
    , points(_alloc)
    , arm(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _ids_type;
  _ids_type ids;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef uint32_t _arm_type;
  _arm_type arm;





  typedef boost::shared_ptr< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ArmBatchTransformRequest_

typedef ::robot_core::ArmBatchTransformRequest_<std::allocator<void> > ArmBatchTransformRequest;

typedef boost::shared_ptr< ::robot_core::ArmBatchTransformRequest > ArmBatchTransformRequestPtr;
typedef boost::shared_ptr< ::robot_core::ArmBatchTransformRequest const> ArmBatchTransformRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_core::ArmBatchTransformRequest_<ContainerAllocator1> & lhs, const ::robot_core::ArmBatchTransformRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ids == rhs.ids &&
    lhs.points == rhs.points &&
    lhs.arm == rhs.arm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_core::ArmBatchTransformRequest_<ContainerAllocator1> & lhs, const ::robot_core::ArmBatchTransformRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79e0c62bd3a742db83d556044872e99c";
  }

  static const char* value(const ::robot_core::ArmBatchTransformRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79e0c62bd3a742dbULL;
  static const uint64_t static_value2 = 0x83d556044872e99cULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_core/ArmBatchTransformRequest";
  }

  static const char* value(const ::robot_core::ArmBatchTransformRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# === Request (Python 發送給 C++ 的請求) ===\n"
"# 每個物體的唯一 ID (用來對應 shared_object 的 index)\n"
"uint32[] ids\n"
"\n"
"# 相機座標列表 (對應上面的 ids)\n"
"geometry_msgs/Point[] points\n"
"\n"
"# arm id(1:left,2:right)\n"
"uint32 arm\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::robot_core::ArmBatchTransformRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ids);
      stream.next(m.points);
      stream.next(m.arm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmBatchTransformRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_core::ArmBatchTransformRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_core::ArmBatchTransformRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "ids: ";
    if (v.ids.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.ids[i]);
    }
    if (v.ids.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "points: ";
    if (v.points.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.points[i]);
    }
    if (v.points.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "arm: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.arm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CORE_MESSAGE_ARMBATCHTRANSFORMREQUEST_H
