// Generated by gencpp from file robot_core/BatchTransformResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_CORE_MESSAGE_BATCHTRANSFORMRESPONSE_H
#define ROBOT_CORE_MESSAGE_BATCHTRANSFORMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace robot_core
{
template <class ContainerAllocator>
struct BatchTransformResponse_
{
  typedef BatchTransformResponse_<ContainerAllocator> Type;

  BatchTransformResponse_()
    : ids()
    , points()
    , success(false)  {
    }
  BatchTransformResponse_(const ContainerAllocator& _alloc)
    : ids(_alloc)
    , points(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _ids_type;
  _ids_type ids;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::robot_core::BatchTransformResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_core::BatchTransformResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BatchTransformResponse_

typedef ::robot_core::BatchTransformResponse_<std::allocator<void> > BatchTransformResponse;

typedef boost::shared_ptr< ::robot_core::BatchTransformResponse > BatchTransformResponsePtr;
typedef boost::shared_ptr< ::robot_core::BatchTransformResponse const> BatchTransformResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_core::BatchTransformResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_core::BatchTransformResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_core::BatchTransformResponse_<ContainerAllocator1> & lhs, const ::robot_core::BatchTransformResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ids == rhs.ids &&
    lhs.points == rhs.points &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_core::BatchTransformResponse_<ContainerAllocator1> & lhs, const ::robot_core::BatchTransformResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_core::BatchTransformResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_core::BatchTransformResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_core::BatchTransformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_core::BatchTransformResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_core::BatchTransformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_core::BatchTransformResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_core::BatchTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5cd09659b70cc339f03c1a36fe033c5";
  }

  static const char* value(const ::robot_core::BatchTransformResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5cd09659b70cc33ULL;
  static const uint64_t static_value2 = 0x9f03c1a36fe033c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_core::BatchTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_core/BatchTransformResponse";
  }

  static const char* value(const ::robot_core::BatchTransformResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_core::BatchTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# === Response (C++ 回傳給 Python 的結果) ===\n"
"# 回傳 ID 以確保順序正確 (通常跟請求的一樣)\n"
"uint32[] ids\n"
"\n"
"# 轉換後的基座標列表\n"
"geometry_msgs/Point[] points\n"
"\n"
"# 是否執行成功\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::robot_core::BatchTransformResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_core::BatchTransformResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ids);
      stream.next(m.points);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BatchTransformResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_core::BatchTransformResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_core::BatchTransformResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "ids: ";
    if (v.ids.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.ids[i]);
    }
    if (v.ids.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "points: ";
    if (v.points.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.points[i]);
    }
    if (v.points.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CORE_MESSAGE_BATCHTRANSFORMRESPONSE_H
