// Generated by gencpp from file robot_core/BatchTransform.msg
// DO NOT EDIT!


#ifndef ROBOT_CORE_MESSAGE_BATCHTRANSFORM_H
#define ROBOT_CORE_MESSAGE_BATCHTRANSFORM_H

#include <ros/service_traits.h>


#include <robot_core/BatchTransformRequest.h>
#include <robot_core/BatchTransformResponse.h>


namespace robot_core
{

struct BatchTransform
{

typedef BatchTransformRequest Request;
typedef BatchTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BatchTransform
} // namespace robot_core


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_core::BatchTransform > {
  static const char* value()
  {
    return "6021b6112a957556fbdf33fd163786a6";
  }

  static const char* value(const ::robot_core::BatchTransform&) { return value(); }
};

template<>
struct DataType< ::robot_core::BatchTransform > {
  static const char* value()
  {
    return "robot_core/BatchTransform";
  }

  static const char* value(const ::robot_core::BatchTransform&) { return value(); }
};


// service_traits::MD5Sum< ::robot_core::BatchTransformRequest> should match
// service_traits::MD5Sum< ::robot_core::BatchTransform >
template<>
struct MD5Sum< ::robot_core::BatchTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_core::BatchTransform >::value();
  }
  static const char* value(const ::robot_core::BatchTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_core::BatchTransformRequest> should match
// service_traits::DataType< ::robot_core::BatchTransform >
template<>
struct DataType< ::robot_core::BatchTransformRequest>
{
  static const char* value()
  {
    return DataType< ::robot_core::BatchTransform >::value();
  }
  static const char* value(const ::robot_core::BatchTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_core::BatchTransformResponse> should match
// service_traits::MD5Sum< ::robot_core::BatchTransform >
template<>
struct MD5Sum< ::robot_core::BatchTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_core::BatchTransform >::value();
  }
  static const char* value(const ::robot_core::BatchTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_core::BatchTransformResponse> should match
// service_traits::DataType< ::robot_core::BatchTransform >
template<>
struct DataType< ::robot_core::BatchTransformResponse>
{
  static const char* value()
  {
    return DataType< ::robot_core::BatchTransform >::value();
  }
  static const char* value(const ::robot_core::BatchTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_CORE_MESSAGE_BATCHTRANSFORM_H
