(cl:defpackage robot_core-srv
  (:use )
  (:export
   "ARMBATCHTRANSFORM"
   "<ARMBATCHTRANSFORM-REQUEST>"
   "ARMBATCHTRANSFORM-REQUEST"
   "<ARMBATCHTRANSFORM-RESPONSE>"
   "ARMBATCHTRANSFORM-RESPONSE"
   "BATCHTRANSFORM"
   "<BATCHTRANSFORM-REQUEST>"
   "BATCHTRANSFORM-REQUEST"
   "<BATCHTRANSFORM-RESPONSE>"
   "BATCHTRANSFORM-RESPONSE"
  ))

