set(_CATKIN_CURRENT_PACKAGE "robot_core")
set(robot_core_VERSION "0.0.0")
set(robot_core_MAINTAINER "airobots <airobots@todo.todo>")
set(robot_core_PACKAGE_FORMAT "2")
set(robot_core_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs" "geometry_msgs" "tf2_ros" "tf2_geometry_msgs")
set(robot_core_BUILD_EXPORT_DEPENDS )
set(robot_core_BUILDTOOL_DEPENDS "catkin")
set(robot_core_BUILDTOOL_EXPORT_DEPENDS )
set(robot_core_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "geometry_msgs" "tf2_ros" "tf2_geometry_msgs")
set(robot_core_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "geometry_msgs" "tf2_ros" "tf2_geometry_msgs")
set(robot_core_TEST_DEPENDS )
set(robot_core_DOC_DEPENDS )
set(robot_core_URL_WEBSITE "")
set(robot_core_URL_BUGTRACKER "")
set(robot_core_URL_REPOSITORY "")
set(robot_core_DEPRECATED "")